/**
 * Frontend configuration.
 * Update BACKEND_URL after deploying the backend to Render.
 * RSA_PUBLIC_KEY_PEM is safe to commit — it is not a secret.
 */
const CONFIG = {
  BACKEND_URL: "https://changraeyu-restaurant-finder-api.hf.space",

  // RSA-2048 public key — generated by backend/scripts/generate_keys.py
  // Used to verify the digital signature on search responses.
  RSA_PUBLIC_KEY_PEM: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3mBjJ51JlgMgXXirfOx1
5A9/5FEzR7x6Xya8WQsM5ClPIwx1ZPWh7xN0q+Warbh/2+AnONgSeEFaeD8hZ1ID
pmVUAW0q3DA8P6otdB7HwUD502M8Bvu4i9CKrs4TaJ5YJQ7WfB7/rcjIPpYPrjOc
IqOpleBHf79A5UGQ4ggtn4LHr3SlznbXy5Mn0YcPCvZ+sr82dhVK9rFXGjwm26GP
ggmASXHGZXnTAOA8YJo+bcTRGjU3NcuyYPRohzvpYDhKv7cxZHACPboRMD+Ob4vY
NBYlP4GTWLXutwbZNRL5CzNjhjDzvvyBa/EN5zFv4fKJY5Z38n0b783N75ah7MZR
AwIDAQAB
-----END PUBLIC KEY-----`,

  DEFAULT_LAT: 24.8138,   // Hsinchu City center fallback
  DEFAULT_LON: 120.9675,
};
